git:
    access_token: ENC[AES256_GCM,data:A/Gu6OfJPlZpysZwTenxaK1AutzvanisACbknvFyHBaevDKEYQgqO79BuFsYwXdqhD6Vkf4aDQqg8iL6oEwqDD9lXYfukXrnkIaCg+Psjbr6JEB2+AebAIdf/HHx,iv:5+XeQJZLdGtMKgerkNefIpWQ/ig06YD+9HbIO3MPEXk=,tag:tIetdFKcumxLAnX0sYgrqg==,type:str]
    config: ENC[AES256_GCM,data:DQttDD/uWYEIpYX+8JxDlUigf5qnU6yEnsKVwVDYVLG4WCnmzNtwkOyCVCN6htXeSpqtdNvCqFgH0o7FOg9e/xXhEIGfsB5arE6jWm3JcUgBlr/ElKPr2cj1K2B4AX6XUGNT1OfBxxjS40iouaKOd994k0DuXtW/5kvK21kUYWend3O3v8Rklg+PWL9zsKelnngDxNlHwMTz4GU=,iv:a1/asROqpARGSsd9S8ZJqmWAX9/GWIOhPcNTckL5b74=,tag:nqUPknB6MFyjH13T6cvbAA==,type:str]
ssh:
    config: ""
    git:
        prv_key: ENC[AES256_GCM,data:vJRSiyxZruZ0nGzHOccFPrEDSCd81ipxOk2SSBL/NzggheHaMxcgg0PoENEz/wyIhtiCq7+1bVpD1eF9TDAdzj9AWinW5ZpwSKzJ32wX0a0IScPJjRKrWnXh4zGnnvUt5BqoD3j6bfB7yFOp1rxxMaydjON5fwsnq2U+doNS02btG+jLqvwY/bUImXxrvpmzlLpRIYEBpmEeTOB6Ki6QJmsoOcYoJDA5ayaUh88uGMYRtOgjTaXTmKJh+s63AM8xdkNXTtFPoGBdcsx1OEiFmNLhEHr0s6tSiLiMzTSP/Tg2GeDf/gLDE+iYwySO/vmiI4t97YZWDBetsudFndZ6xc2x8y+Sl/EEb/CwdDY50RD+do5B+mzNtKuuwXhM5IlIe7USht8j0kQALLM/wr/JsKuvKXLyk5Z2xQhKeVt6LW1ILLNiC7GyG0xcqZ/pNed8+cYXSq4WY1UzLVoiRHczmTVLbMajsT36kPCBGWkD1kH+HPAoDokkeaHyvOGBmvXQRhTpdIRcWvltVxX3BMlJNgfUIALO9QAAkbjh,iv:9s/PmqgH6MDdEIOLTKCeiVvnVWsACqUKYnajmCWoS4w=,tag:yJRv+8Cw/5K9hc++H62gTw==,type:str]
        pub_key: ENC[AES256_GCM,data:njPL+XVEXb8GEhQCXebgtE0SsAqaM8U3SMTzOUNVMBn+HhHNlHoeyWPTY8av66u2hjEQvFWLy3k2NYgMQfJeRcwi+Y3uJJMjSStVpgho8yDYO06xmUQJhs8AaQHiphw+,iv:zOvCKl2u8ktxWwMZIX/zDy2Xb3+UZvVa724GXgT2/BY=,tag:4Xg3LrsxPCTDq9mp4kuLsg==,type:str]
github:
    access_token_for_dotfiles: ENC[AES256_GCM,data:ANv53JDf5a/mcGkf3RlNac2qZmhRr2h0+qmF8robpr1s2d9moa8lUg5UXPrutuSJeQwByWxnPbg0ZEg6b9XAIzcxQvsEkQOIwHSHDmLU8ka5vQ0TBnAkelsJmHzx,iv:UybrAk72/tCmnqEz+x26sRN9u8xH9ENtbHp65nvFfr0=,tag:uU31zFBQx9mOJIEizQhPzg==,type:str]
ai:
    opencode:
        env: ENC[AES256_GCM,data:Pd0GYlH4jwunfKrvDfW0qoFm7QIRICP3K2CqG4Az+wLW0v7IXmwuSQyYF2O1NQMu46lm4y+tEhsXU5cGgs0U2Q==,iv:acvgu2PT/7L0LtkxQI3MAXuq0bNvxeOW9fLovm+VMpg=,tag:coY7QQ8wLhMq6C7ipKlHTg==,type:str]
    deepseek:
        api-key: ENC[AES256_GCM,data:L06Eaj47VYyzmX0VD0GOwgiQ5bvwTe2fhbKyL8QMpRpkRmI=,iv:Gwuhi8QtxcgzdxkkiTrBn6tpIJESq5hzpsnaO7rJucw=,tag:2bkMzpeT8Oas+oEVu98s1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3hiMnhxSVVucXBTc2U2
            Y0VUZFNycEJiNWFzUDdDblFBbFQ0WlpPZlZNCmF6UGZxdjZ3WUtLNFJHZDJVV3RF
            ajliNmhTODdaNUtNTnlQbEZCUTd2Z1EKLS0tIDk2dkU5bEM2TDI4WmxaSzBwZ2Iw
            NVpWMHBhT05ZL1EveElRcnk4N2t0VzgK+3SoToFsjthOGigwzZA0QHfOji2Hrurl
            FGofZdVaYFKFxXbiri2BqtZDwEg08ntXYX+L020osTa2xU4YKgBoPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p495yz2np3kxa03qs2370nsl4jsv22fggs3r3wq7zv6nqn4n29xqg0znr9
    lastmodified: "2026-06-17T03:09:10Z"
    mac: ENC[AES256_GCM,data:DHOjSueNxdmb/cR4i0Quc1JxOC6sAwjjDeHyRV4VzFs8KbBPAcVLrz5NdklxS7t+ethcBYSb5+2pirmG7XvtPtUqyLdj0dZCz8K52ILOV3e1MGrT65VSThRVc2sLLApPZy80m5+2MNFWQPAjDDkZmVB4DC0NyfqVIIVfQBaOcnU=,iv:ZXsXlaCSzX6doht7b6y2k1dibj1VTDhKshilf695sGg=,tag:Xr2bStWFVYrHNs3IpVv21w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
