git:
    access_token: ENC[AES256_GCM,data:A/Gu6OfJPlZpysZwTenxaK1AutzvanisACbknvFyHBaevDKEYQgqO79BuFsYwXdqhD6Vkf4aDQqg8iL6oEwqDD9lXYfukXrnkIaCg+Psjbr6JEB2+AebAIdf/HHx,iv:5+XeQJZLdGtMKgerkNefIpWQ/ig06YD+9HbIO3MPEXk=,tag:tIetdFKcumxLAnX0sYgrqg==,type:str]
    config: ENC[AES256_GCM,data:DQttDD/uWYEIpYX+8JxDlUigf5qnU6yEnsKVwVDYVLG4WCnmzNtwkOyCVCN6htXeSpqtdNvCqFgH0o7FOg9e/xXhEIGfsB5arE6jWm3JcUgBlr/ElKPr2cj1K2B4AX6XUGNT1OfBxxjS40iouaKOd994k0DuXtW/5kvK21kUYWend3O3v8Rklg+PWL9zsKelnngDxNlHwMTz4GU=,iv:a1/asROqpARGSsd9S8ZJqmWAX9/GWIOhPcNTckL5b74=,tag:nqUPknB6MFyjH13T6cvbAA==,type:str]
ssh:
    config: ""
    git:
        private_key: ENC[AES256_GCM,data:6msL3oUXjZjOepSs/IJLVy8L15aOfiR0czJZHsDtWGOrJA1xwb2GIPI3F7TF8sStnpqgrYu+h+TU6dXrKyhcghkt/2biOs69TbT3ihKYBx0r2Mj2WpIBm/aaKDb259cnN2WgvF3/eNf0Ej576d5yXjiZSZ0OqSJUGA6WmrBjgZr3obRHlDTYvgLogKIBtJKHELl6OwnpyC7PE2hgriKe/gykhmHCMVLAMGbnu2CTaXPsdB41d5zGQhGMiQxWHkBci0art/Uw3vvuLKMenidUVZ2T5wIOgWQQX9BxdDAuL+G/MLshnVXOHWbV7NyLHEqAjxBOxdQGf+Pz1h9G9S/zDaU5B9prPRXBzQVRgS8aYBK7KNz5yIZdUo3PzWVW30mq3+mDG9ubidL/7Iy1hG9Y52PyWR/GCu5My8AE8hV5v7FCrq3qF/DvB6mZ09fRxziy3lVHf5+2phn16h+EDUigABNBYZryqtchFMRZCFC2b5Z/tPjzHXXocm+NWTJugkR21+td+OOEmXnvGBsV8su3lYCe+uDtcsV9dBUG,iv:VHjP/j4nv0WEaq+uqoixVmGTN12rTvx/QZKW9znQegg=,tag:bf1bM1uXoW2ILvEYFe752A==,type:str]
        public_key: ENC[AES256_GCM,data:RcgBI1gyicKn7Ccha3kcbY2oRKfomqwwiOkk+BWmXTBOFoXaIqLiKjuVZ3vqTnzAKFE2EfNndPCdj4e7XcQLzk7thJmIskBcbxmOe1LXxX7w4/4C5YnnDblWl3veRg4/,iv:yATXT63e0/wtKoC8BtXMpsGmXm6ZkybokDi4yuhK9/A=,tag:lfOsi47dh8w5Pmk5A7k5qw==,type:str]
github:
    access_token_for_dotfiles: ENC[AES256_GCM,data:Jwauozpn9wm37aqwgSLpXYpIj4NBX6lXwbacqDMtGBHGHq6d6Kqfvg==,iv:aNzL6/9fQFFFSyDJnH4SY5fbYieVNr1cXm6yxxT22Aw=,tag:lfhHecQh8R4y1AOI41XlPw==,type:str]
ai:
    opencode:
        env: ENC[AES256_GCM,data:Pd0GYlH4jwunfKrvDfW0qoFm7QIRICP3K2CqG4Az+wLW0v7IXmwuSQyYF2O1NQMu46lm4y+tEhsXU5cGgs0U2Q==,iv:acvgu2PT/7L0LtkxQI3MAXuq0bNvxeOW9fLovm+VMpg=,tag:coY7QQ8wLhMq6C7ipKlHTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3hiMnhxSVVucXBTc2U2
            Y0VUZFNycEJiNWFzUDdDblFBbFQ0WlpPZlZNCmF6UGZxdjZ3WUtLNFJHZDJVV3RF
            ajliNmhTODdaNUtNTnlQbEZCUTd2Z1EKLS0tIDk2dkU5bEM2TDI4WmxaSzBwZ2Iw
            NVpWMHBhT05ZL1EveElRcnk4N2t0VzgK+3SoToFsjthOGigwzZA0QHfOji2Hrurl
            FGofZdVaYFKFxXbiri2BqtZDwEg08ntXYX+L020osTa2xU4YKgBoPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p495yz2np3kxa03qs2370nsl4jsv22fggs3r3wq7zv6nqn4n29xqg0znr9
    lastmodified: "2026-06-07T19:35:30Z"
    mac: ENC[AES256_GCM,data:d04uoK3z1hdwBqIvTFG5k28B/WITvqEjrWfvoiV8oQ+F9P0BM5Gx4glsx9wOK6Jfwx5p66X0VQHc690lzqCBjtZ4MdsIY8QbOLOQuMIoyI97eSWKEikjo/OaaFIcne2aen5Bsn/fwL58c+APeWNi2i201w8tkURkL1+8tWOheqw=,iv:PXVO3lAodoDEAclehdfGb3r7Q1Z4DBZi9USHHHqJesQ=,tag:uzg4L/YJVmhLl0rGgCNhcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
