test: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RUx6T2k5NG12Y1JiL1J5
            Q0lkNnNyRm90aUVFTTZlcFhyWFBwUWU2VWdBCktoL04vb0o5b1NNQzJnMldUL2pQ
            T01kRndGV011THpZVWVnNHI5UmlMc2cKLS0tIHV6aWNyZUQzNXIwM1loYldtLzdl
            K2xXSDVNdmxvZkp0VG1aanFCVXVYQzgKn2EOR59Er64D9fk+TqOGqiYb6M5uYowC
            UHOcgoNZvJ6by0/fcJLJFVytQx7+23JUe6VCAuuvybN0iBSB3eJx2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138fermrnh7d7sczchptuz29e5gph44fk2tfg8u74e4yk5c0r6qwqkulx62
    lastmodified: "2026-07-27T07:37:23Z"
    mac: ENC[AES256_GCM,data:qEOpXnnXwnpQOBxfsQO/ER26ApCSh3kKY2rl3cruc+hDd0P8llK+5gAJm/1LlzlybWcc3c0TGnznV2DZ9OasJ/XhLKKbdh7rKyx/aXNhvG9ND0XPRoSeDHYWJlEim1P5rritMCRl4W6aEKrsbVGG2MoQ4Rxhe78oEQA0fER8mEI=,iv:s/M/dC+f7igFN3Ed9vm/deILJ0SkgNKaVpCqccP8zwQ=,tag:PuwD41Dsb6kS1K0N1qITXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
