test: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZN0F4ZWhBZE1XcXM0SzdN
            dXVwL25oRzNLWDlUNG9Zcys4bGZhZ2pLVUZFCkZlQi9JbXZWRU45RnpRQk0rVk9G
            NGxkRHdvK0grWVVqTVdRdzZKK1pVTDAKLS0tIExITFQ4UXM5Y2xmYzhqWVA4ZEQ3
            VzRjZ1NwbTlseDFKdlBYMjN1MEFGaW8KEDH4CRvCwHLKlQLrrYv9zo9t2r0acVyV
            tqpXShOIOu0edjORg/pjjsBTukDqi3ZG0vSNy/A5Y84R/YYMUkjIfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12uuq6kpu8tavla9jfsu3wz5s5dwfpyv6vcv7gd54a06294w22p4q9mvh9m
    lastmodified: "2026-07-27T07:37:05Z"
    mac: ENC[AES256_GCM,data:hytXkF5KJqth+Ttl++iiy87NSWNv6YwoJLAPhfB12XzEB8GG8TvC1dG0a/x3otOPoJTGS06uTpvs7tBJMknO8QG+vcPEggKkSg13MJFEQpKjj7D1lGSi0ayPsDXZ2/tMSnTB3jEqxkiX0W1/GZUQ0eZkIdNTBa6fwxRMa+wMaLY=,iv:xXTEyIYTfarn/eHVgPEqrd8e/NF1+o2un1GT4rfylao=,tag:Sh3XhYbE477tCeQjPqexhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
