ai:
    deepseek:
        api-key: ENC[AES256_GCM,data:L91iLy57qM5VVqWfuxD2CgNlOHSd3xUZNjlCGbbEf+nUe2A=,iv:ooQnU6N2uqQcJ9yj9+ND5n2RnvM+g4RukGIH2c++QRs=,tag:41yZoVVpg+073ghYgXcFMg==,type:str]
dockhand:
    #ENC[AES256_GCM,data:FwL3nxOTB6uiQyelLYQ6T5aIyYCz32Oop5rQ+5z9b6hms/uE9aooxtSbWNBP49vP2KasAhBpuTqABdBnOHSEkWC4Qk59,iv:D9sgTOOgaUlzmV69Dz+Xao2FBD9/nUK35Xr0bqgeeq8=,tag:dcBQo+YpKjEjCRmRuhJqyQ==,type:comment]
    #
    #ENC[AES256_GCM,data:cL5x1AGm8yR69v9gGGEuFiA4D/BbTp35xGtmK8+dtEbD5qbwpEw+5w==,iv:1Df1X5QHZ4vOQvW+QjAzM2MNR/eb+G3pWEyaVivWsxY=,tag:S1q9iay5oAVJdXSO5I/eYA==,type:comment]
    #
    #ENC[AES256_GCM,data:NxdtuszuFXtjPrCaDn3gLQzZeWvx7qH+4ehngqHFVX8Lonk=,iv:K0TEKe86TSRGLXMHXeqO/P2Me5G5HHVY6mwfe5EJmMk=,tag:mwp2GJZFV640qwr0xRBXCg==,type:comment]
    env: ENC[AES256_GCM,data:/fWs9WBh3CEXXuB8RSg71LXt5N6dJDzI4FNnM7Qc1hc0TyLtJ67ULslYpfphvXSUOK/zvP28s73V3MwGQKRQy7h9WVwHS9/xqHbCWjRse3PkZZ01WL+Pv4tBJPY=,iv:Nl9sMfUvAYQrP897d72UGgfjVE/qNZLfWUV6McXQrLg=,tag:6R4F1WaKqWyQdqaqDDfyVg==,type:str]
sonarqube:
    env: ENC[AES256_GCM,data:DFw3DM2ni0XWXdmZRFW3HAirBC//tyuVbX+ozxvjaW4s6/PAh+bey4oa2up+VRlQpaqP3+xyRlwOgnq/zJ7szjIZCd3szr6OsuygYg+Or71zMo+Htck+jsM7sMRMMyuSHvlyDFfIaNU5RECs6oX8YBlwMkBMZAmZQvPVo9RtfaLxv7D94Q==,iv:nxXgRGwEW0Y6FBCfwhZfwjN8P7GN4pHzGz96MyJSwR4=,tag:1eBJ6uPw/yV4tS29ZiOA3Q==,type:str]
postgres:
    dockhand:
        env: ENC[AES256_GCM,data:gF0mXa1D8v4D8/0YIohvFY9aWHcHFyBp3kLY94qWgtyF4FtRRkXUYiDemgK09ZfoopGN/d5jtwhC/9KOtNgiJy6ZPhaE6CVDwPy6lyTEkafYtUc=,iv:z2/GUrZdaGL/sPzmZWFdU5Pt8Up9+zSvCNXIjbJNPak=,tag:t8RgwT2d8MCvOS+YHZr35w==,type:str]
    sonarqube:
        env: ENC[AES256_GCM,data:5nRrOMWYZBs0oMLbymTc6AQ6xbr77zX33jP2zVcFWTF4ixeg8RPJHDe3WScrC7IgQRC2tTOZc/R9ZfqDEbpdTreP3xegGn9/9KiGovD+OvuEaD8x2g==,iv:TmHirBnf7dJEN50x0AD+4nroGXl743wVKNwr9p6iFB8=,tag:RYzHHgA2uCNP2eGDVfOaUg==,type:str]
nix:
    #ENC[AES256_GCM,data:e2yd+tZ4kaSDZVDnS7xoOeTXdEJt0R6+VCCfiPEHY4LNgHHe9XG8HWtEUx8Y9e/rgL5mRICV4BDJpDOas5M=,iv:jf/T9dXgIw5FXTtEt5u1ulTq7mdLzMVm6eYpg7bFpqo=,tag:1I9f5rBzcHVZt7jCGSInpA==,type:comment]
    extra-options: ENC[AES256_GCM,data:+/t3q9qutZkE4T+kHhP8SeQu9sXUNrJKYGnUCOtQeIhM+bo+iKbhPfh1wUSW7HsPCSEt2HTqeOQBDlEymWRnizZHzfr1qVDG4NEdb4zJXkSAnEDN4xZ41J+Ol+L7Mbu/QOtIOYG5txFmeR9yHgVfsEfPDjAMYvAakA==,iv:DIW3KwpvztYqUr0gfk1COYbpNd2879O0dvWKwOn1jpI=,tag:6MD1zm5/fgVUiouli0kD/A==,type:str]
music-server:
    env: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZmI1b3lBWlpENFhrNjgx
            Y3NURG1Ja2RKWlhsQ0RpZ2lsR3FpTmtabG5vCnN4ZERqYzBsbVRjdmJFbElNaThp
            LzdpUnpyTHE3REhJM2IzWTZSSWFSTHMKLS0tIDJJRXdKV01rR1VIVGhMZzJNMzZp
            alNVWTJsLzg3dlhpdnRkbEJxc2lKQzgKVPxHVXHh1rP4Ja6/+opdQr9wCKPi/Kno
            P2gYsjl439KQMyWJ393zIaAA/jzJtgwXThcJl4Wrmr7dhZ9GkN/fLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq3sazn8wsdedjhw367cns4tf80kr63usdgu3szpfv2s8ntqdesq2mpa4q
    lastmodified: "2026-07-24T03:23:29Z"
    mac: ENC[AES256_GCM,data:+Gx0qE5GL0cM3DddATkofi6Ql8x3I0F9wpCOsZ2a4adJH3V71eo+YNquBGe83qeqOz0sVtS1/ONKKkLAtqJSuDQH8SjF0l3wUBdTy0WozR7u2O9L2nzbDl2nOb0yBDn23OTAOJvb/ps+R9mNBk+m8lrNNxd/qhLkyzzipQ1Nw54=,iv:eF/RxaQ1YP8JyG6Gimmg6hj74AozVBtDtKlR+lRa9oo=,tag:7eJr4WdXDpLhxV8hU7AQXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
