ai:
    deepseek:
        api-key: ENC[AES256_GCM,data:L91iLy57qM5VVqWfuxD2CgNlOHSd3xUZNjlCGbbEf+nUe2A=,iv:ooQnU6N2uqQcJ9yj9+ND5n2RnvM+g4RukGIH2c++QRs=,tag:41yZoVVpg+073ghYgXcFMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZmI1b3lBWlpENFhrNjgx
            Y3NURG1Ja2RKWlhsQ0RpZ2lsR3FpTmtabG5vCnN4ZERqYzBsbVRjdmJFbElNaThp
            LzdpUnpyTHE3REhJM2IzWTZSSWFSTHMKLS0tIDJJRXdKV01rR1VIVGhMZzJNMzZp
            alNVWTJsLzg3dlhpdnRkbEJxc2lKQzgKVPxHVXHh1rP4Ja6/+opdQr9wCKPi/Kno
            P2gYsjl439KQMyWJ393zIaAA/jzJtgwXThcJl4Wrmr7dhZ9GkN/fLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uq3sazn8wsdedjhw367cns4tf80kr63usdgu3szpfv2s8ntqdesq2mpa4q
    lastmodified: "2026-06-17T05:28:21Z"
    mac: ENC[AES256_GCM,data:1pzbf/7K8YUojWmAOhATann5i0MpQdrCY1wRGnHXUtl/WJsCRZTANk4v45cqwP5VWdm2ogUwm7iscNp04Yo0gpUdy6NU4Va4Gdn/oo8y90aE1YsiPxLNIbJummaaNWYO65Bje2NlwgxuKPc9S8sl8+ZgJ3X7yc7ni4krRjNaKJA=,iv:XV8r5K19Vey3lBKtplJRKHsXO4VMCUVIV4vx6sX3PNg=,tag:KlZUJOw17vr7zTPSgHxmdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
